

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    jackson:
        serialization:
            indent-output: true
    datasource:
        url: jdbc:mysql://localhost:3306/work?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: pass1234
        driver-class-name: com.mysql.jdbc.Driver

server:
    port: 9090
    servlet:
        context-path: /work
