spring:
    # 环境 dev|prod
    profiles:
        active: dev
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                # 方言
                dialect: org.hibernate.dialect.MySQL5Dialect
                # 使用懒加载必须配置
                enable_lazy_load_no_trans: true
                # 是否打印sql
                show_sql: true
                format_sql: false
                use_sql_comments: true
    # jackson时间格式化
    # 不然返回的Date格式不正常（2019-05-08T09:28:34.000+0000）
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            indent-output: true
    http:
        encoding:
            charset: utf-8
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: 127.0.0.1
        port: 6379
        password:    # 密码（默认为空）
        timeout: 6000ms  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
    mvc:
        throw-exception-if-no-handler-found: true

server:
    # Tomcat
    tomcat:
        uri-encoding: UTF-8
        #最大连接数
        max-threads: 200
        #最大连接数
        max-connections: 300
        #最小连接备用数
        min-spare-threads: 30
        #post提交数据最大大小，设置为0不限制
        max-http-post-size: 0
    port: 8081
    connection-timeout: 5000ms
    servlet:
        context-path: /work
