spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                # 使用懒加载必须配置
                enable_lazy_load_no_trans: true
                # 是否打印sql
                show_sql: true
                format_sql: false
                use_sql_comments: true
    jackson:
        serialization:
            indent-output: true
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/work?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#        url: jdbc:mysql://172.17.0.2:3306/work?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: pass1234
        driver-class-name: com.mysql.jdbc.Driver
    http:
        encoding:
            charset: utf-8
            enabled: true
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true

server:
    # Tomcat
    tomcat:
        uri-encoding: UTF-8
        #最大连接数
        max-threads: 200
        #最大连接数
        max-connections: 300
        #最小连接备用数
        min-spare-threads: 30
        #post提交数据最大大小，设置为0不限制
        max-http-post-size: 0
    port: 8081
    servlet:
        context-path: /work

# 文件保存路径
stream:
    http:
        multipart:
#            file: D:/resource/file/
#            video: D:/resource/video/
          file:  /home/file/
          video: /home/video/

